
import java.util.ArrayList;
import java.util.Date;
import java.util.Calendar;
import javax.swing.JOptionPane;



public class JanelaPrincipal extends javax.swing.JFrame {
    static ArrayList<Usuario> users = new ArrayList();
    static ArrayList<Recurso> recs = new ArrayList();
    static ArrayList<Emprestimo> emps = new ArrayList();
    static ArrayList<Sessao> ses = new ArrayList();
    static ArrayList<SessaoUsuario> su = new ArrayList();
    JanelaUsuario telaUser;
    JanelaRecurso telaRec;
    JanelaEmprestimo telaEmp;
    JanelaSessao telaSes;
    
    Date dataBusca;
    
     public static void diretoNoCodigo()
       {
           Usuario p1 = new Professor("João Silva", "111000111-00", 10, 1000, "9999-5555", "01/04/1980", false);
           Usuario p2 = new Professor("Pedro José", "123000321-45", 11, 1020, "8485-8584", "08/04/1975", true);
           users.add(p1);
           users.add(p2);
           
           Usuario a1 = new Aluno("Paulo Carlos", 20, 1000, "8444-5050", "10/12/1968", "Carlos Paulo", "Carla de Paula");
           Usuario a2 = new Aluno("Luis Antonio", 21, 1020, "8156-4713", "07/07/1977", "Antonio Luis", "Luiza Antonia");
           users.add(a1);
           users.add(a2);
           
           Recurso f1 = new Filme("Vida no Brasil", 50, 1960, "Documentário", "10 anos");
           Recurso f2 = new Filme("Fúria do Olimpo", 51, 2010, "Ficção Científica", "Livre");
           recs.add(f1);
           recs.add(f2);
           
           Recurso r1 = new Revista("Revista Nacional de Artes", 60, 1990, "Outubro", "Cultura", "NSE", 2);
           Recurso r2 = new Revista("Revista Nacional de Saúde", 61, 1946, "Março", "Saúde", "Lin", 4); 
           recs.add(r1);
           recs.add(r2);
           
           Emprestimo e1 = new Emprestimo (70, "22/03/2010", p1);
           e1.insereItemRecurso(2, r2);
           Emprestimo e2 = new Emprestimo (71, "16/02/2014", a1);
           e2.insereItemRecurso(5, r1);
           emps.add(e1);
           emps.add(e2); 
           
           Sessao s1 = new Sessao(80, "15/05/2015/","14:00", r1, 3);
           Sessao s2 = new Sessao(81, "24/09/2015/","19:00", r2, 4);
           ses.add(s1);
           ses.add(s2);
           
           SessaoUsuario su1 = new SessaoUsuario(a1,s1);
           SessaoUsuario su2 = new SessaoUsuario(a2,s2);
           SessaoUsuario su3 = new SessaoUsuario(p1,s2);
           SessaoUsuario su4 = new SessaoUsuario(p2,s1);
           su.add(su1);
           su.add(su2);
           su.add(su3);
           su.add(su4);
           
       }

    public JanelaPrincipal() {
        diretoNoCodigo();
        initComponents();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuUsuario = new javax.swing.JMenuItem();
        menuRecurso = new javax.swing.JMenuItem();
        menuEmprestimo = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setText("Cadastrar");
        jMenu1.setContentAreaFilled(false);
        jMenu1.setPreferredSize(new java.awt.Dimension(60, 60));

        menuUsuario.setText("Usuário");
        menuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(menuUsuario);

        menuRecurso.setText("Recurso");
        menuRecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRecursoActionPerformed(evt);
            }
        });
        jMenu1.add(menuRecurso);

        menuEmprestimo.setText("Empréstimo");
        menuEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmprestimoActionPerformed(evt);
            }
        });
        jMenu1.add(menuEmprestimo);

        jMenuItem5.setText("Sessão de filme");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu2.setText("Imprimir");

        jMenuItem1.setText("Usuários");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Recursos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem4.setText("Empréstimos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem6.setText("Empréstimos por data de empréstimo");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Empréstimos por data limite");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Sessões");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Sessões por data");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuItem10.setText("Relação de participantes de sessões");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarioActionPerformed
        if(telaUser == null)
        {
            telaUser = new JanelaUsuario(users);
        }
        telaUser.setVisible(true);
    }//GEN-LAST:event_menuUsuarioActionPerformed

    private void menuRecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRecursoActionPerformed
        if(telaRec == null)
        {
            telaRec = new JanelaRecurso(recs);
        }
        telaRec.setVisible(true);
    }//GEN-LAST:event_menuRecursoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String saida = "";
        for(Usuario u: users){
            saida = saida + " Nome: " +  u.getNome() + " Código: " +  u.getCodUsuario() + "\n";
        }
        JOptionPane.showMessageDialog(null, saida);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        String saida = "";
        for(Recurso r: recs){
            saida = saida + " Nome: " +  r.getNome() + " Código: " + r.getCodRecurso() + "\n";
        }
        JOptionPane.showMessageDialog(null, saida);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmprestimoActionPerformed
    if(telaEmp == null)
        {
            telaEmp = new JanelaEmprestimo(users, recs, emps);
        }
        telaEmp.setVisible(true);
    }//GEN-LAST:event_menuEmprestimoActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        String saida = "";
        for(Emprestimo e: emps){
            saida = saida + "Código do empréstimo: " + e.getCodEmprestimo() + " Usuário: " + e.getU().getNome() + " Data: " + e.getDataEmprestimo() + "\n";
        }
        JOptionPane.showMessageDialog(null, saida);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        if(telaSes == null)
        {
            telaSes = new JanelaSessao(users, recs, ses, su);
        }
        telaSes.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
    dataBusca = new Date(JOptionPane.showInputDialog("Digite a data do empréstimo para busca"));
        for(Emprestimo emp : emps)
        {
            if(emp.getDataEmprestimo() == dataBusca);
            JOptionPane.showMessageDialog(null, emp);
        }       
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        dataBusca = new Date(JOptionPane.showInputDialog("Digite a data limite do empréstimo para busca"));
        for(Emprestimo emp : emps)
        {
            if(emp.getDataLimite() == dataBusca);
            JOptionPane.showMessageDialog(null, emp);
        } 
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        for(Sessao s : ses)
        {
            JOptionPane.showMessageDialog(null, s);
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        dataBusca = new Date(JOptionPane.showInputDialog("Digite a data da sessão para busca"));
        for(Sessao s : ses)
        {
            if(s.getDataSessao() == dataBusca);
            JOptionPane.showMessageDialog(null, s);
            return;
        }
        JOptionPane.showMessageDialog(null, "Sessão não cadastrada");
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        String saida="";
        
        for (Sessao s : ses)
        {
            saida +=  s.getCodSessao() + "\n";
            for (SessaoUsuario SeUs : su)
            {
                if (s == SeUs.getSessao())
                    saida += "\t" + SeUs.getUsuario().getNome() + "\n";
            }
            saida+="\n";
        }
        JOptionPane.showMessageDialog(null,saida);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem menuEmprestimo;
    private javax.swing.JMenuItem menuRecurso;
    private javax.swing.JMenuItem menuUsuario;
    // End of variables declaration//GEN-END:variables
}
